### ISSUE TITLE
Initialize VPN service with fresh databases

### ISSUE THREAD

**Issue by bmah888** [esnet/enos#109]
On an installation with new databases, the initialization of the VPN service objects and associated database collections falls over in various ways.

```
admin@NetShell> cd /lib/layer2/vpn
changed to: /lib/layer2/vpn

admin@NetShell> vpn logging /tmp/enos.log 
Traceback (most recent call last):
  File "/home/enos/distro/netshell-root/lib/layer2/vpn/vpn.py", line 1055, in <module>
    vpnService = VPNService()
  File "/home/enos/distro/netshell-root/lib/layer2/vpn/vpn.py", line 167, in __init__
    self.loadService()
  File "/home/enos/distro/netshell-root/lib/layer2/vpn/vpn.py", line 199, in loadService
    self.topology = Container.getContainer(self.properties['topology'])
KeyError: topology
Traceback (most recent call last):
  File "/home/enos/distro/netshell-root/lib/layer2/vpn/vpn.py", line 1055, in <module>
    vpnService = VPNService()
  File "/home/enos/distro/netshell-root/lib/layer2/vpn/vpn.py", line 167, in __init__
    self.loadService()
  File "/home/enos/distro/netshell-root/lib/layer2/vpn/vpn.py", line 199, in loadService
    self.topology = Container.getContainer(self.properties['topology'])
KeyError: 'topology'
```

I think the problem has to do with the implicit setting up of global variables before command-line processing, and before we have a chance to set the two topology properties.  We might need to make the startup of the listeners explicit.  Hacking around this now to get a deployment running but we need to fix this in code.

**Comment by lomaxfrog** [comment]
The problem was due to a change in the Container semantics after a feature request that Container.getContainer() creates a container if it does not exist yet. The persistency VPN code was written before and was not making that assumption.

**Comment by bmah888** [comment]
Seems to be OK now. Note that another, related code change (dabcc033383f8427544067d7809c9f789ec09c84) changed the initial workflow so that it's now `vpn settopos` to set the topology databases, followed by `vpn startup` to start the service for the first time.  But no errors now with this workflow.
