### ISSUE TITLE
Problems when deleting a VPN site

### ISSUE THREAD

**Issue by bmah888** [esnet/enos#18]
```
admin@NetShell> reload 

admin@NetShell> demo 
VPN environment is ready.

admin@NetShell> vpn create vpn1
VPN vpn1 is created successfully.

admin@NetShell> vpn vpn1 addpop denv
Pop denv is added into VPN vpn1 successfully.

admin@NetShell> vpn vpn1 addpop aofa
Pop aofa is added into VPN vpn1 successfully.

admin@NetShell> vpn vpn1 addsite lbl.gov
The site lbl.gov is added into VPN vpn1 successfully

admin@NetShell> vpn vpn1 addsite bnl.gov
The site bnl.gov is added into VPN vpn1 successfully

admin@NetShell> vpn vpn1 delsite bnl.gov 
Traceback (most recent call last):
  File "/home/enos/distro/netshell-root/lib/layer2/vpn/vpn.py", line 398, in <module>
    main()
  File "/home/enos/distro/netshell-root/lib/layer2/vpn/vpn.py", line 354, in main
    delsite(vpn, site)
  File "/home/enos/distro/netshell-root/lib/layer2/vpn/vpn.py", line 276, in delsite
    popsRenderer.delSite(site)
  File "/home/enos/distro/netshell-root/lib/layer2/vpn/l2vpn.py", line 840, in delSite
    swSwitchScope.delEndpoint(swSwitch.props['vmPort'], siteVlan)
  File "/home/enos/distro/netshell-root/lib/layer2/common/openflow.py", line 696, in delEndpoint
    if not port.name in self.props['endpoints']:
AttributeError: 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/home/enos/distro/netshell-root/lib/layer2/vpn/vpn.py", line 398, in <module>
    main()
  File "/home/enos/distro/netshell-root/lib/layer2/vpn/vpn.py", line 354, in main
    delsite(vpn, site)
  File "/home/enos/distro/netshell-root/lib/layer2/vpn/vpn.py", line 276, in delsite
    popsRenderer.delSite(site)
  File "/home/enos/distro/netshell-root/lib/layer2/vpn/l2vpn.py", line 840, in delSite
    swSwitchScope.delEndpoint(swSwitch.props['vmPort'], siteVlan)
  File "/home/enos/distro/netshell-root/lib/layer2/common/openflow.py", line 696, in delEndpoint
    if not port.name in self.props['endpoints']:
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by bmah888** [comment]
This issue has been overtaken by events, notably the complete rewrite of the VPN code.  We don't see this behavior on current code.

Closing.
